string=input("Enter the string: ")
alphanumeric=any(char.isalnum() for char in string)
print(alphanumeric)
alphabetical=any(char.isalpha() for char in string)
print(alphabetical)
digits=any(char.isdigit() for char in string)
print(digits)
lowercase=any(char.islower() for char in string)
print(lowercase)
uppercase=any(char.isupper() for char in string)
print(uppercase)